### ISSUE TITLE
How does it grab thumbnails?

### ISSUE THREAD

**Issue by johhnyspringer** [shopgirl284/RSSFeed.bundle#8]
Hey, I manage my own RSS feeds and am wondering how the plugin pulls thumbnails. I am currently using <media:thumbnails, but it ins't working. Could you please shed some light on this?

**Comment by shopgirl284** [comment]
If you are asking to make sure an RSS feed XML document you have created is designed properly, the main image or icon for the RSS feed is pulled from the plugins database, if the user has entered an html address for it manually. Otherwise, it is pulled from a child tag called image of the channel tag for the feed.  And thumbnails for each entry in the feed is first looked for in a child tag called image of each item tag (pulls the text within the tag) and then the description child tag of each item is searched for an img tag with a src value . 

If you are wanting to add custom images for an existing RSS feed, you can add an alternative show icon by choosing the add image option within a feed results listing and typing or pasting the full html address of an icon available on the Internet into the entry field. You cannot add custom images for individual feed items.

**Comment by shopgirl284** [comment]
Old issue closing
